// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmxSvkDQxlf5e5-PtiO_Lq1uJG3o40UTI',
    appId: '1:194927244974:android:1fde5fd014686074351f3f',
    messagingSenderId: '194927244974',
    projectId: 'moapp-teamp',
    storageBucket: 'moapp-teamp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWSHUHwJ9CCuZoCyN9cLL94R_5SrrvP3U',
    appId: '1:194927244974:ios:9bf1cffdf5d11866351f3f',
    messagingSenderId: '194927244974',
    projectId: 'moapp-teamp',
    storageBucket: 'moapp-teamp.firebasestorage.app',
    androidClientId: '194927244974-vk3r1uv594rai9a0pd8ojmlvflfg09l0.apps.googleusercontent.com',
    iosClientId: '194927244974-at7k6p52fsqq313qvlqgvml3r5ihst0k.apps.googleusercontent.com',
    iosBundleId: 'com.example.pixelNSemicolon',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAixpRzc3YydlvH0jpIY9hS88BTQFomduA',
    appId: '1:194927244974:web:3b1ac893b68cc949351f3f',
    messagingSenderId: '194927244974',
    projectId: 'moapp-teamp',
    authDomain: 'moapp-teamp.firebaseapp.com',
    storageBucket: 'moapp-teamp.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWSHUHwJ9CCuZoCyN9cLL94R_5SrrvP3U',
    appId: '1:194927244974:ios:9bf1cffdf5d11866351f3f',
    messagingSenderId: '194927244974',
    projectId: 'moapp-teamp',
    storageBucket: 'moapp-teamp.firebasestorage.app',
    androidClientId: '194927244974-vk3r1uv594rai9a0pd8ojmlvflfg09l0.apps.googleusercontent.com',
    iosClientId: '194927244974-at7k6p52fsqq313qvlqgvml3r5ihst0k.apps.googleusercontent.com',
    iosBundleId: 'com.example.pixelNSemicolon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAixpRzc3YydlvH0jpIY9hS88BTQFomduA',
    appId: '1:194927244974:web:ea5f73653f202f6a351f3f',
    messagingSenderId: '194927244974',
    projectId: 'moapp-teamp',
    authDomain: 'moapp-teamp.firebaseapp.com',
    storageBucket: 'moapp-teamp.firebasestorage.app',
  );

}