// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTJ_ckEPHT04oXyAe40cz2_nEl-OxXTgU',
    appId: '1:506241724506:web:30d31aa55fa063b7b1a863',
    messagingSenderId: '506241724506',
    projectId: 'moappfinal-e52a2',
    authDomain: 'moappfinal-e52a2.firebaseapp.com',
    storageBucket: 'moappfinal-e52a2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyOg8RonVO-W6HR1DW7aN2DcwayC7sWr8',
    appId: '1:506241724506:android:3e0e01b3924e9a6cb1a863',
    messagingSenderId: '506241724506',
    projectId: 'moappfinal-e52a2',
    storageBucket: 'moappfinal-e52a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAW5z4Urq61cx5c2IByyRGoPFxMtDV_Z40',
    appId: '1:506241724506:ios:1c456da29ddd77cdb1a863',
    messagingSenderId: '506241724506',
    projectId: 'moappfinal-e52a2',
    storageBucket: 'moappfinal-e52a2.firebasestorage.app',
    iosClientId: '506241724506-ueg7d3ed58kpvfeqrse9a69cm7ak7e95.apps.googleusercontent.com',
    iosBundleId: 'com.example.mdc100Series',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAW5z4Urq61cx5c2IByyRGoPFxMtDV_Z40',
    appId: '1:506241724506:ios:1c456da29ddd77cdb1a863',
    messagingSenderId: '506241724506',
    projectId: 'moappfinal-e52a2',
    storageBucket: 'moappfinal-e52a2.firebasestorage.app',
    iosClientId: '506241724506-ueg7d3ed58kpvfeqrse9a69cm7ak7e95.apps.googleusercontent.com',
    iosBundleId: 'com.example.mdc100Series',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTJ_ckEPHT04oXyAe40cz2_nEl-OxXTgU',
    appId: '1:506241724506:web:ac86c6ad6cbb2327b1a863',
    messagingSenderId: '506241724506',
    projectId: 'moappfinal-e52a2',
    authDomain: 'moappfinal-e52a2.firebaseapp.com',
    storageBucket: 'moappfinal-e52a2.firebasestorage.app',
  );
}
