// Copyright 2018-present the Flutter authors. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import 'product.dart';

class ProductsRepository {
  static List<Product> loadProducts(Category category) {
    const allProducts = <Product>[
      Product(
        category: Category.accessories,
        id: 0,
        isFeatured: true,
        name: 'Grand Luxury Hotel',
        price: 250,
        rating: 5,
        location: '123 5th Avenue, New York, NY 10001',
        description: 'Experience luxury at its finest with stunning city views, world-class amenities, and exceptional service in the heart of Manhattan. Our hotel features spacious suites, fine dining restaurants, spa facilities, and 24-hour room service.',
        phoneNumber: '+1 212 555 0123',
        imageUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
      ),
      Product(
        category: Category.accessories,
        id: 1,
        isFeatured: true,
        name: 'Ocean View Resort',
        price: 180,
        rating: 4,
        location: '21050 Pacific Coast Hwy, Malibu, CA 90265',
        description: 'A beautiful beachfront resort offering pristine ocean views, spa services, and direct beach access for the perfect getaway. Enjoy our infinity pool, beachside bar, and world-class wellness center.',
        phoneNumber: '+1 310 555 0456',
        imageUrl: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
      ),
      Product(
        category: Category.accessories,
        id: 2,
        isFeatured: false,
        name: 'Mountain Lodge',
        price: 120,
        rating: 4,
        location: '675 Lionshead Pl, Vail, CO 81657',
        description: 'Cozy mountain retreat surrounded by nature with hiking trails, fireplace rooms, and stunning mountain vistas. Perfect for winter skiing and summer hiking adventures.',
        phoneNumber: '+1 970 555 0789',
        imageUrl: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
      ),
      Product(
        category: Category.accessories,
        id: 3,
        isFeatured: true,
        name: 'City Center Hotel',
        price: 160,
        rating: 5,
        location: '900 W Olympic Blvd, Los Angeles, CA 90015',
        description: 'Modern hotel in the heart of LA with rooftop pool, fitness center, and easy access to major attractions. Features contemporary design and premium amenities.',
        phoneNumber: '+1 213 555 0321',
        imageUrl: 'https://images.unsplash.com/photo-1564501049412-61c2a3083791?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
      ),
      Product(
        category: Category.accessories,
        id: 4,
        isFeatured: false,
        name: 'Boutique Inn',
        price: 95,
        rating: 4,
        location: '444 Presidio Ave, San Francisco, CA 94115',
        description: 'Charming boutique hotel with unique décor, personalized service, and prime location near Union Square. Experience intimate luxury with artisanal amenities.',
        phoneNumber: '+1 415 555 0654',
        imageUrl: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
      ),
      Product(
        category: Category.accessories,
        id: 5,
        isFeatured: false,
        name: 'Business Hotel',
        price: 140,
        rating: 4,
        location: '320 N Dearborn St, Chicago, IL 60654',
        description: 'Modern business hotel with conference facilities, executive lounge, and convenient airport shuttle service. Perfect for corporate travelers.',
        phoneNumber: '+1 312 555 0987',
        imageUrl: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
      ),
      Product(
        category: Category.accessories,
        id: 6,
        isFeatured: false,
        name: 'Riverside Resort',
        price: 200,
        rating: 5,
        location: '1510 SW Harbor Way, Portland, OR 97201',
        description: 'Peaceful riverside resort offering kayaking, fishing, spa treatments, and farm-to-table dining experiences. Surrounded by nature and tranquility.',
        phoneNumber: '+1 503 555 0147',
        imageUrl: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
      ),
      Product(
        category: Category.accessories,
        id: 7,
        isFeatured: true,
        name: 'Historic Hotel',
        price: 175,
        rating: 5,
        location: '60 School St, Boston, MA 02108',
        description: 'Elegant historic hotel with classic architecture, fine dining restaurant, and rich cultural heritage. Located in the heart of historic Boston.',
        phoneNumber: '+1 617 555 0258',
        imageUrl: 'https://images.unsplash.com/photo-1590490360182-c33d57733427?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
      ),
      Product(
        category: Category.accessories,
        id: 8,
        isFeatured: true,
        name: 'Desert Oasis',
        price: 220,
        rating: 4,
        location: '5594 E Camelback Rd, Phoenix, AZ 85018',
        description: 'Luxury desert resort featuring golf course, multiple pools, spa services, and stunning desert landscapes. Experience the beauty of the Sonoran Desert.',
        phoneNumber: '+1 602 555 0369',
        imageUrl: 'https://images.unsplash.com/photo-1540541338287-41700207dee6?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
      ),
      Product(
        category: Category.accessories,
        id: 9,
        isFeatured: true,
        name: 'Lakeside Resort',
        price: 195,
        rating: 4,
        location: '1899 Lake Shore Dr, Lake Tahoe, CA 96150',
        description: 'Stunning lakeside resort with panoramic water views, private beach access, water sports, and luxury spa treatments. Perfect for romantic getaways.',
        phoneNumber: '+1 530 555 0741',
        imageUrl: 'https://images.unsplash.com/photo-1549294413-26f195200c16?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
      ),
      Product(
        category: Category.accessories,
        id: 10,
        isFeatured: false,
        name: 'Urban Boutique Hotel',
        price: 135,
        rating: 4,
        location: '1425 Broadway, Seattle, WA 98122',
        description: 'Trendy boutique hotel in downtown Seattle with modern amenities, rooftop bar, and walking distance to Pike Place Market and waterfront.',
        phoneNumber: '+1 206 555 0852',
        imageUrl: 'https://images.unsplash.com/photo-1586611292717-f828b167408c?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
      ),
      Product(
        category: Category.accessories,
        id: 11,
        isFeatured: false,
        name: 'Countryside Inn',
        price: 110,
        rating: 4,
        location: '2847 Country Road, Napa Valley, CA 94558',
        description: 'Charming countryside inn surrounded by vineyards, offering wine tours, farm-to-table dining, and peaceful garden setting.',
        phoneNumber: '+1 707 555 0963',
        imageUrl: 'https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
      ),
      Product(
        category: Category.accessories,
        id: 12,
        isFeatured: false,
        name: 'Beachfront Paradise',
        price: 285,
        rating: 5,
        location: '789 Ocean Drive, Miami Beach, FL 33139',
        description: 'Luxury beachfront hotel with direct ocean access, world-class dining, infinity pools, and vibrant nightlife scene.',
        phoneNumber: '+1 305 555 0174',
        imageUrl: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
      ),
      Product(
        category: Category.accessories,
        id: 13,
        isFeatured: true,
        name: 'Mountain Peak Lodge',
        price: 165,
        rating: 4,
        location: '456 Summit Trail, Aspen, CO 81611',
        description: 'Rustic mountain lodge with ski-in/ski-out access, cozy fireplaces, hot tubs, and breathtaking alpine views.',
        phoneNumber: '+1 970 555 0285',
        imageUrl: 'https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
      ),
      Product(
        category: Category.accessories,
        id: 14,
        isFeatured: true,
        name: 'Art Deco Hotel',
        price: 190,
        rating: 5,
        location: '1234 Collins Ave, Miami Beach, FL 33139',
        description: 'Iconic Art Deco hotel with vintage charm, rooftop pool, gourmet restaurant, and prime South Beach location.',
        phoneNumber: '+1 305 555 0396',
        imageUrl: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
      ),
      Product(
        category: Category.accessories,
        id: 15,
        isFeatured: true,
        name: 'Garden Retreat',
        price: 125,
        rating: 4,
        location: '678 Garden Lane, Savannah, GA 31401',
        description: 'Peaceful garden retreat with lush landscaping, spa services, afternoon tea, and southern hospitality charm.',
        phoneNumber: '+1 912 555 0407',
        imageUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
      ),
      Product(
        category: Category.accessories,
        id: 16,
        isFeatured: true,
        name: 'Skyline Hotel',
        price: 210,
        rating: 5,
        location: '890 Park Ave, New York, NY 10075',
        description: 'Luxury hotel with stunning skyline views, Michelin-starred restaurant, concierge services, and Central Park proximity.',
        phoneNumber: '+1 212 555 0518',
        imageUrl: 'https://images.unsplash.com/photo-1568084680786-a84f91d1153c?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
      ),
      Product(
        category: Category.accessories,
        id: 17,
        isFeatured: false,
        name: 'Coastal Resort',
        price: 175,
        rating: 4,
        location: '321 Coastal Hwy, Big Sur, CA 93920',
        description: 'Dramatic coastal resort perched on cliffs with ocean views, hiking trails, spa treatments, and fine dining experiences.',
        phoneNumber: '+1 831 555 0629',
        imageUrl: 'https://images.unsplash.com/photo-1602002418082-a4443e081dd1?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
      ),
      Product(
        category: Category.accessories,
        id: 18,
        isFeatured: true,
        name: 'Metropolitan Hotel',
        price: 155,
        rating: 4,
        location: '567 Main St, Nashville, TN 37203',
        description: 'Modern metropolitan hotel in Music City with live entertainment, rooftop bar, fitness center, and music venue access.',
        phoneNumber: '+1 615 555 0730',
        imageUrl: 'https://images.unsplash.com/photo-1551918120-9739cb430c6d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
      ),
      Product(
        category: Category.accessories,
        id: 19,
        isFeatured: false,
        name: 'Wellness Spa Hotel',
        price: 245,
        rating: 5,
        location: '123 Wellness Way, Sedona, AZ 86336',
        description: 'Holistic wellness resort offering spa treatments, meditation gardens, yoga classes, and healthy cuisine in red rock country.',
        phoneNumber: '+1 928 555 0841',
        imageUrl: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
      ),
      Product(
        category: Category.accessories,
        id: 20,
        isFeatured: false,
        name: 'Vineyard Hotel',
        price: 180,
        rating: 4,
        location: '456 Grape St, Sonoma, CA 95476',
        description: 'Elegant vineyard hotel with wine tastings, gourmet dining, romantic suites, and stunning valley views.',
        phoneNumber: '+1 707 555 0952',
        imageUrl: 'https://images.unsplash.com/photo-1587061949409-02df41d5e562?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
      ),
      Product(
        category: Category.accessories,
        id: 21,
        isFeatured: false,
        name: 'Riverside Lodge',
        price: 95,
        rating: 3,
        location: '789 River Bend, Jackson, WY 83001',
        description: 'Rustic riverside lodge with fishing guides, wildlife viewing, hiking trails, and cozy cabin accommodations.',
        phoneNumber: '+1 307 555 0163',
        imageUrl: 'https://images.unsplash.com/photo-1549294413-26f195200c16?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
      ),
      Product(
        category: Category.accessories,
        id: 22,
        isFeatured: false,
        name: 'Executive Suites',
        price: 220,
        rating: 5,
        location: '147 Business Blvd, Atlanta, GA 30309',
        description: 'Premium executive hotel with business center, conference rooms, airport shuttle, and luxury amenities for corporate travelers.',
        phoneNumber: '+1 404 555 0274',
        imageUrl: 'https://images.unsplash.com/photo-1560472354-b33ff0c44a43?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
      ),
      Product(
        category: Category.accessories,
        id: 23,
        isFeatured: false,
        name: 'Island Paradise Resort',
        price: 320,
        rating: 5,
        location: '258 Paradise Cove, Key West, FL 33040',
        description: 'Tropical island resort with overwater bungalows, snorkeling, sunset cruises, and Caribbean-inspired cuisine.',
        phoneNumber: '+1 305 555 0385',
        imageUrl: 'https://images.unsplash.com/photo-1540541338287-41700207dee6?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
      ),
      Product(
        category: Category.accessories,
        id: 24,
        isFeatured: true,
        name: 'Ski Chalet Hotel',
        price: 195,
        rating: 4,
        location: '369 Alpine Dr, Park City, UT 84060',
        description: 'Cozy ski chalet with slope access, hot tubs, fireplaces, and après-ski dining in a winter wonderland setting.',
        phoneNumber: '+1 435 555 0496',
        imageUrl: 'https://images.unsplash.com/photo-1551524164-6cf307ad0806?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
      ),
      Product(
        category: Category.accessories,
        id: 25,
        isFeatured: false,
        name: 'Heritage Hotel',
        price: 165,
        rating: 4,
        location: '741 Historic Ave, Charleston, SC 29401',
        description: 'Beautifully restored heritage hotel with antique furnishings, southern cuisine, ghost tours, and historic charm.',
        phoneNumber: '+1 843 555 0507',
        imageUrl: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
      ),
      Product(
        category: Category.accessories,
        id: 26,
        isFeatured: false,
        name: 'Airport Hotel',
        price: 89,
        rating: 3,
        location: '852 Terminal Dr, Denver, CO 80249',
        description: 'Convenient airport hotel with shuttle service, business facilities, fitness center, and comfortable accommodations.',
        phoneNumber: '+1 303 555 0618',
        imageUrl: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
      ),
      Product(
        category: Category.accessories,
        id: 27,
        isFeatured: true,
        name: 'Boutique Loft Hotel',
        price: 175,
        rating: 4,
        location: '963 Loft St, Portland, OR 97205',
        description: 'Hip boutique hotel in converted loft building with industrial design, craft cocktails, local art, and urban culture.',
        phoneNumber: '+1 503 555 0729',
        imageUrl: 'https://images.unsplash.com/photo-1586611292717-f828b167408c?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
      ),
      Product(
        category: Category.accessories,
        id: 28,
        isFeatured: true,
        name: 'Surfside Resort',
        price: 155,
        rating: 4,
        location: '159 Surf Ave, San Diego, CA 92109',
        description: 'Beachfront surf resort with board rentals, surf lessons, beach volleyball, and casual oceanside dining.',
        phoneNumber: '+1 619 555 0830',
        imageUrl: 'https://images.unsplash.com/photo-1602002418082-a4443e081dd1?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
      ),
      Product(
        category: Category.accessories,
        id: 29,
        isFeatured: true,
        name: 'Castle Hotel',
        price: 275,
        rating: 5,
        location: '357 Castle Hill, Newport, RI 02840',
        description: 'Majestic castle hotel with grand ballrooms, formal gardens, afternoon tea, and breathtaking ocean views.',
        phoneNumber: '+1 401 555 0941',
        imageUrl: 'https://images.unsplash.com/photo-1590490360182-c33d57733427?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
      ),
      Product(
        category: Category.accessories,
        id: 30,
        isFeatured: true,
        name: 'Eco-Lodge Resort',
        price: 140,
        rating: 4,
        location: '468 Nature Trail, Olympic Peninsula, WA 98382',
        description: 'Sustainable eco-lodge with renewable energy, organic gardens, wildlife viewing, and environmental education programs.',
        phoneNumber: '+1 360 555 0152',
        imageUrl: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
      ),
      Product(
        category: Category.accessories,
        id: 31,
        isFeatured: false,
        name: 'Downtown Suites',
        price: 125,
        rating: 4,
        location: '579 Main St, Austin, TX 78701',
        description: 'Modern downtown suites with kitchenettes, live music venues nearby, rooftop pool, and vibrant nightlife access.',
        phoneNumber: '+1 512 555 0263',
        imageUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
      ),
      Product(
        category: Category.accessories,
        id: 32,
        isFeatured: false,
        name: 'Golf Resort Hotel',
        price: 205,
        rating: 4,
        location: '680 Fairway Dr, Scottsdale, AZ 85260',
        description: 'Championship golf resort with multiple courses, pro shop, golf lessons, spa services, and desert dining experiences.',
        phoneNumber: '+1 480 555 0374',
        imageUrl: 'https://images.unsplash.com/photo-1586375300773-8384e3e4916f?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
      ),
      Product(
        category: Category.accessories,
        id: 33,
        isFeatured: true,
        name: 'Thermal Springs Hotel',
        price: 185,
        rating: 4,
        location: '791 Hot Springs Rd, Yellowstone, MT 59047',
        description: 'Natural thermal springs hotel with healing waters, spa treatments, wilderness tours, and rustic luxury accommodations.',
        phoneNumber: '+1 406 555 0485',
        imageUrl: 'https://images.unsplash.com/photo-1578683010236-d716f9a3f461?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
      ),
      Product(
        category: Category.accessories,
        id: 34,
        isFeatured: false,
        name: 'Family Resort Hotel',
        price: 145,
        rating: 4,
        location: '802 Family Fun Blvd, Orlando, FL 32819',
        description: 'Family-friendly resort with water slides, kids club, character dining, theme park shuttles, and entertainment programs.',
        phoneNumber: '+1 407 555 0596',
        imageUrl: 'https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
      ),
      Product(
        category: Category.accessories,
        id: 35,
        isFeatured: false,
        name: 'Budget Inn & Suites',
        price: 65,
        rating: 3,
        location: '913 Budget Way, Las Vegas, NV 89103',
        description: 'Affordable accommodations with clean rooms, continental breakfast, pool, and convenient Strip access for budget travelers.',
        phoneNumber: '+1 702 555 0607',
        imageUrl: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
      ),
      Product(
        category: Category.accessories,
        id: 36,
        isFeatured: false,
        name: 'Rooftop Hotel',
        price: 190,
        rating: 4,
        location: '246 Skyline Dr, San Francisco, CA 94102',
        description: 'Trendy rooftop hotel with panoramic city views, rooftop bar, modern design, and walking distance to Union Square.',
        phoneNumber: '+1 415 555 0718',
        imageUrl: 'https://images.unsplash.com/photo-1574691250077-03a929faece5?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
      ),
      Product(
        category: Category.accessories,
        id: 37,
        isFeatured: true,
        name: 'Luxury Penthouse Hotel',
        price: 385,
        rating: 5,
        location: '135 Penthouse Ave, Las Vegas, NV 89109',
        description: 'Ultra-luxury penthouse hotel with butler service, private elevators, high-end shopping, world-class entertainment, and VIP experiences.',
        phoneNumber: '+1 702 555 0829',
        imageUrl: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
      ),
    ];
    if (category == Category.all) {
      return allProducts;
    } else {
      return allProducts.where((Product p) {
        return p.category == category;
      }).toList();
    }
  }
}
